# 13 — Agente de Cobranza Autónomo Level 3
## Desarrollo, prueba y demostración del grafo LangGraph

**Objetivo de este notebook:**  
Construir, validar y documentar el Agente de Cobranza Level 3 de forma aislada,  
antes de integrarlo en `tab_cobranza.py`. Cada sección prueba un escenario distinto  
del grafo para verificar que los 7 nodos, los edges condicionales y las 4 tools  
funcionan correctamente con clientes reales del seed.

**¿Por qué Level 3?**  
El agente no solo recomienda — ejecuta acciones con efectos persistentes en el CRM  
sin aprobación humana por acción individual. El humano supervisa el `log_decisiones`,  
no cada paso. Nivel 4 requeriría orquestación multi-agente y planificación temporal  
extendida (mejora futura documentada).

---
**Flujo del grafo:**
```
enriquecer_contexto → evaluar_riesgo → decidir_accion
                                              │
                          ┌───────────────────┼──────────────────┐
                     tool_call=None        tool_call          error
                          │                   │                  │
                         END           ejecutar_accion    registrar_error
                                              │                  │
                                   ┌──────────┴──────┐          │
                               ok/negocio          error        END
                                   │                  │
                           registrar_decision   registrar_error
                                   │                  │
                                  END                END
```

## 0 · Setup

In [1]:
import os
from pathlib import Path
from dotenv import load_dotenv

# Fix SSL — eliminar variable que apunta a archivo inexistente
ssl_path = os.environ.get("SSL_CERT_FILE", "")
if ssl_path and not Path(ssl_path).exists():
    os.environ.pop("SSL_CERT_FILE")
    print(f"SSL_CERT_FILE eliminada ✓  (era: {ssl_path})")

# Cargar .env del proyecto
load_dotenv()

# Verificar
print(f"ANTHROPIC_API_KEY: {'presente ✓' if os.environ.get('ANTHROPIC_API_KEY') else 'AUSENTE ✗'}")

SSL_CERT_FILE eliminada ✓  (era: C:\Users\Marin\.conda\envs\credit-risk/ssl/cacert.pem)
ANTHROPIC_API_KEY: presente ✓

In [2]:
import sys
import os
from pathlib import Path

# Detectar root del proyecto automáticamente
# Funciona tanto si el notebook está en la raíz como en notebooks/
_cwd = Path.cwd()
if (_cwd / "src" / "crm").exists():
    PROJECT_ROOT = _cwd
elif (_cwd.parent / "src" / "crm").exists():
    PROJECT_ROOT = _cwd.parent
else:
    raise RuntimeError(
        "No se encontró src/crm/. "
        "Ejecuta este notebook desde la raíz del proyecto."
    )

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print(f"PROJECT_ROOT: {PROJECT_ROOT}")
print(f"src/crm existe: {(PROJECT_ROOT / 'src' / 'crm').exists()}")

PROJECT_ROOT: C:\Users\Marin\Documents\PROYECTO ML_OPS\credit-risk-scoring-ml
src/crm existe: True

In [3]:
import sqlite3
import json
import pandas as pd
pd.set_option("display.max_colwidth", 80)
pd.set_option("display.max_columns", 20)
pd.set_option("display.width", 120)

from src.crm import (
    inicializar_crm,
    get_db_path,
    consultar_cliente,
    TOOLS_AGENTE,
    EtapaCobranza,
    evaluar_pausa,
    ejecutar_agente,
    ejecutar_lote_ews,
    ResultadoAgente,
    grafo_cobranza,
)

print("Imports OK")
print(f"Tools disponibles: {[t.name for t in TOOLS_AGENTE]}")

Imports OK
Tools disponibles: ['registrar_contacto', 'actualizar_estado', 'escalar_caso', 'generar_propuesta']

## 1 · Inicializar CRM

Reset completo del CRM para garantizar un estado limpio y reproducible.  
`force_reset=True` elimina todos los datos y resiembra los 23 clientes sintéticos.

In [4]:
inicializar_crm(force_reset=True)

con = sqlite3.connect(get_db_path())
print("CRM inicializado:", get_db_path())
print()

# Resumen de tablas
for tabla in ["clientes", "contactos", "escalaciones", "propuestas", "log_decisiones"]:
    n = con.execute(f"SELECT COUNT(*) FROM {tabla}").fetchone()[0]
    print(f"  {tabla:<22} {n:>3} registros")

print()
# Clientes por etapa
df_etapas = pd.read_sql(
    "SELECT etapa_cobranza, COUNT(*) as clientes, "
    "ROUND(AVG(ews_score),3) as ews_prom, "
    "ROUND(AVG(dias_mora),1) as mora_prom, "
    "ROUND(AVG(monto_adeudado),0) as monto_prom "
    "FROM clientes GROUP BY etapa_cobranza "
    "ORDER BY MIN(CASE etapa_cobranza "
    "WHEN 'preventiva' THEN 0 WHEN 'temprana' THEN 1 "
    "WHEN 'administrativa' THEN 2 WHEN 'judicial' THEN 3 ELSE 4 END)",
    con
)
print("Clientes por etapa:")
display(df_etapas)
con.close()

CRM inicializado: C:\Users\Marin\Documents\PROYECTO ML_OPS\credit-risk-scoring-ml\src\crm\cobranza_crm.db

  clientes                23 registros
  contactos               38 registros
  escalaciones             4 registros
  propuestas               5 registros
  log_decisiones           2 registros

Clientes por etapa:

   etapa_cobranza  clientes  ews_prom  mora_prom  monto_prom
0      preventiva         5     0.698        5.8     12510.0
1        temprana         6     0.787       29.2     25700.0
2  administrativa         4     0.847       76.3     44025.0
3        judicial         4     0.903      147.0     62425.0
4         castigo         4     0.955      296.3     52675.0

## 2 · Verificación de componentes

Antes de ejecutar el grafo completo, verificamos que `consultar_cliente()` devuelve  
el contexto correcto y que `evaluar_pausa()` identifica correctamente los casos  
que requieren confirmación humana en modo autónomo.

In [5]:
# Contexto de CLI006 — temprana, 4 intentos fallidos
ctx_006 = consultar_cliente("CLI006")
print(f"Cliente: {ctx_006.nombre}")
print(f"  EWS Score:         {ctx_006.ews_score:.3f}")
print(f"  Días de mora:      {ctx_006.dias_mora}")
print(f"  Monto adeudado:    ${ctx_006.monto_adeudado:,.2f}")
print(f"  Etapa:             {ctx_006.etapa_cobranza}")
print(f"  Intentos fallidos: {ctx_006.intentos_fallidos}")
print(f"  Gestionado humano: {ctx_006.gestionado_humano}")
print()
print("Últimos contactos:")
for c in ctx_006.ultimos_contactos:
    print(f"  [{c.timestamp[:10]}] {c.canal:10} → {c.resultado}")

Cliente: Roberto Jiménez Cruz
  EWS Score:         0.780
  Días de mora:      18
  Monto adeudado:    $22,400.00
  Etapa:             temprana
  Intentos fallidos: 4
  Gestionado humano: False

Últimos contactos:
  [2026-06-05] sms        → no_contesto
  [2026-06-01] llamada    → contesto
  [2026-05-29] whatsapp   → no_contesto

In [6]:
# Verificar evaluar_pausa para distintos perfiles
casos_pausa = [
    ("CLI001", "preventiva,  $12.5k,  1 intento fallido"),
    ("CLI006", "temprana,    $22.4k,  4 intentos fallidos"),
    ("CLI009", "temprana,    $44k,    5+ intentos fallidos"),
    ("CLI012", "administrativa, $53.2k, 6 intentos"),
    ("CLI016", "judicial,    $78.6k,  3 intentos"),
    ("CLI018", "judicial,    $92.1k,  5+ intentos"),
]

print(f"{'Cliente':<8} {'Descripción':<45} {'Requiere pausa'}")
print("-" * 70)
for cid, desc in casos_pausa:
    ctx = consultar_cliente(cid)
    pausa = evaluar_pausa(ctx)
    marca = "✓ SÍ" if pausa else "  no"
    print(f"{cid:<8} {desc:<45} {marca}")

Cliente  Descripción                                   Requiere pausa
----------------------------------------------------------------------
CLI001   preventiva,  $12.5k,  1 intento fallido         no
CLI006   temprana,    $22.4k,  4 intentos fallidos       no
CLI009   temprana,    $44k,    5+ intentos fallidos      no
CLI012   administrativa, $53.2k, 6 intentos            ✓ SÍ
CLI016   judicial,    $78.6k,  3 intentos              ✓ SÍ
CLI018   judicial,    $92.1k,  5+ intentos             ✓ SÍ

## 3 · Estructura del grafo compilado

In [7]:
# Visualización en Mermaid (renderiza en Jupyter con extensión o en GitHub)
try:
    mermaid_str = grafo_cobranza.get_graph().draw_mermaid()
    print(mermaid_str)
except Exception:
    # Fallback: ASCII
    print(grafo_cobranza.get_graph().draw_ascii())

---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	enriquecer_contexto(enriquecer_contexto)
	evaluar_riesgo(evaluar_riesgo)
	decidir_accion(decidir_accion)
	ejecutar_accion(ejecutar_accion)
	registrar_decision(registrar_decision)
	registrar_error(registrar_error)
	__end__([<p>__end__</p>]):::last
	__start__ --> enriquecer_contexto;
	decidir_accion -.-> __end__;
	decidir_accion -.-> ejecutar_accion;
	decidir_accion -.-> registrar_error;
	ejecutar_accion -.-> registrar_decision;
	ejecutar_accion -.-> registrar_error;
	enriquecer_contexto -.-> evaluar_riesgo;
	enriquecer_contexto -.-> registrar_error;
	evaluar_riesgo -.-> decidir_accion;
	evaluar_riesgo -.-> registrar_error;
	registrar_decision --> __end__;
	registrar_error --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc

In [8]:
# Nodos y edges del grafo compilado
print("Nodos:", sorted(grafo_cobranza.nodes))
print()
print("Edges:")
for edge in grafo_cobranza.get_graph().edges:
    print(f"  {edge[0]} → {edge[1]}")

Nodos: ['__start__', 'decidir_accion', 'ejecutar_accion', 'enriquecer_contexto', 'evaluar_riesgo', 'registrar_decision', 'registrar_error']

Edges:
  __start__ → enriquecer_contexto
  decidir_accion → __end__
  decidir_accion → ejecutar_accion
  decidir_accion → registrar_error
  ejecutar_accion → registrar_decision
  ejecutar_accion → registrar_error
  enriquecer_contexto → evaluar_riesgo
  enriquecer_contexto → registrar_error
  evaluar_riesgo → decidir_accion
  evaluar_riesgo → registrar_error
  registrar_decision → __end__
  registrar_error → __end__

## 4 · Escenario A — Gestión normal (modo asistido)

**Cliente:** CLI006 — Roberto Jiménez Cruz  
**Perfil:** Etapa temprana, 18 días de mora, 4 intentos fallidos, $22,400 adeudados.  
**Modo:** Asistido (`modo_autonomo=False`) — el agente recomienda y ejecuta.  
**Esperado:** El grafo completa el ciclo, elige una tool y registra la decisión en el log.

In [9]:
print("Ejecutando agente para CLI006 (modo asistido)...")
print("=" * 60)

resultado_a = ejecutar_agente("CLI006", modo_autonomo=False)

print(f"Acción tomada:         {resultado_a.accion_tomada}")
print(f"Urgencia evaluada:     {resultado_a.urgencia}")
print(f"Resultado OK:          {resultado_a.resultado_ok}")
print(f"Mensaje:               {resultado_a.mensaje_resultado}")
print(f"Requiere confirmación: {resultado_a.requiere_confirmacion}")
print(f"Error:                 {resultado_a.error}")
print()
print("Razonamiento del agente:")
print(resultado_a.razonamiento)

Ejecutando agente para CLI006 (modo asistido)...
============================================================
Acción tomada:         escalar_caso
Urgencia evaluada:     media
Resultado OK:          True
Mensaje:               Caso escalado a supervisor. Trigger autónomo suspendido. Requiere resolución humana desde Tab 6.
Requiere confirmación: False
Error:                 None

Razonamiento del agente:
Cliente presenta EWS Score elevado (0.780) indicando riesgo significativo. Con 18 días de mora y $22,400 adeudados (22.4% del límite), ha incumplido promesa de pago explícita del 2026-06-01. Los 4 intentos fallidos sin respuesta sugieren evasión deliberada. La etapa TEMPRANA es insuficiente dado el patrón de incumplimiento. Transición a ADMINISTRATIVA justificada porque: (1) cliente tuvo oportunidad de regularizar con promesa verbal, (2) requiere intervención humana para negociación estructurada, (3) aún no amerita judicial pero necesita presión formal. EWS Score >0.75 indica probabilidad alta de default si no se actúa. Prioridad: obtener compromiso de pago verificable en 5 días o iniciar trámite de notificación formal. Sin contexto normativo CNBV disponible, se aplican restricciones estándar de cobranza responsable.

In [10]:
# Verificar que la acción quedó registrada en el log
con = sqlite3.connect(get_db_path())
df_log_a = pd.read_sql(
    "SELECT log_id, nodo_origen, tool_llamada, status, timestamp "
    "FROM log_decisiones WHERE cliente_id='CLI006' ORDER BY timestamp DESC LIMIT 3",
    con
)
con.close()
print("Log de decisiones — CLI006 (últimas 3 entradas):")
display(df_log_a)

Log de decisiones — CLI006 (últimas 3 entradas):

        log_id      nodo_origen        tool_llamada status            timestamp
0  LOGA87AF076  ejecutar_accion        escalar_caso     ok  2026-06-08 16:32:29
1  LOG746633CD   decidir_accion  registrar_contacto     ok  2026-06-05 16:32:14

## 5 · Escenario B — Cliente judicial en modo autónomo (pausa obligatoria)

**Cliente:** CLI016 — Arturo Medina Fuentes  
**Perfil:** Etapa judicial, 135 días de mora, monto $78,600 (> $50k), rechazo explícito.  
**Modo:** Autónomo (`modo_autonomo=True`)  
**Esperado:** `requiere_confirmacion=True` — el agente evalúa y decide pero Tab 6 debe  
pedir aprobación antes de ejecutar. El grafo NO ejecuta la acción automáticamente  
cuando `requiere_confirmacion=True` ya que la verificación es responsabilidad de la  
capa de presentación.

> **Nota de diseño:** Este es el mecanismo que diferencia Level 3 de un agente  
> completamente sin supervisión. El humano aprueba casos críticos, no cada paso.

In [11]:
print("Ejecutando agente para CLI016 (modo autónomo — caso judicial)...")
print("=" * 60)

resultado_b = ejecutar_agente("CLI016", modo_autonomo=True)

print(f"Acción tomada:         {resultado_b.accion_tomada}")
print(f"Urgencia evaluada:     {resultado_b.urgencia}")
print(f"Requiere confirmación: {resultado_b.requiere_confirmacion}")
print(f"Resultado OK:          {resultado_b.resultado_ok}")
print(f"Error:                 {resultado_b.error}")
print()
print("Razonamiento:")
print(resultado_b.razonamiento)

Ejecutando agente para CLI016 (modo autónomo — caso judicial)...
============================================================
Acción tomada:         sin_accion
Urgencia evaluada:     alta
Requiere confirmación: True
Resultado OK:          False
Error:                 None

Razonamiento:
Cliente en etapa judicial con EWS crítico (0.910), mora severa (135 días) y monto significativo ($78,600). Ha rechazado explícitamente contacto directo en dos ocasiones consecutivas, manifestando representación legal. Continuar con intentos de contacto directo viola normativa CNBV sobre acoso y desconoce derecho del cliente a representación. La escalación legal está pendiente y es el canal apropiado. El cliente no responde a gestión preventiva/temprana; la etapa judicial es correcta. Prioridad: contactar representante legal para agilizar procedimiento y evitar sanciones CNBV por prácticas coercitivas. Suspender intentos de contacto directo inmediatamente.

## 6 · Escenario C — Cliente con escalación activa (gestionado_humano=True)

**Cliente:** CLI014 — Héctor Guzmán Lara  
**Perfil:** Etapa administrativa, 3 promesas incumplidas, escalado a supervisor.  
`gestionado_humano=True` — el trigger autónomo está suspendido hasta resolución humana.  
**Esperado:** El nodo `decidir_accion` detecta `gestionado_humano=True`, no llama ninguna  
tool, y el grafo termina por el edge condicional `tool_call=None → END`.

In [12]:
# Verificar estado previo
ctx_014 = consultar_cliente("CLI014")
print(f"CLI014 | gestionado_humano: {ctx_014.gestionado_humano}")
print(f"Escalaciones activas: {len(ctx_014.escalaciones_activas)}")
for e in ctx_014.escalaciones_activas:
    print(f"  [{e.nivel}] {e.motivo[:70]}")
print()

print("Ejecutando agente para CLI014...")
print("=" * 60)
resultado_c = ejecutar_agente("CLI014", modo_autonomo=True)

print(f"Acción tomada:         {resultado_c.accion_tomada}")
print(f"Requiere confirmación: {resultado_c.requiere_confirmacion}")
print(f"Error:                 {resultado_c.error}")
print()
if resultado_c.accion_tomada == "sin_accion":
    print("✓ Correcto: el agente respetó el bloqueo por escalación activa.")

CLI014 | gestionado_humano: True
Escalaciones activas: 1
  [supervisor] Tres promesas de pago incumplidas en 90 días de mora. Sin acuerdo viab

Ejecutando agente para CLI014...
============================================================
Acción tomada:         sin_accion
Requiere confirmación: True
Error:                 None

✓ Correcto: el agente respetó el bloqueo por escalación activa.

## 7 · Escenario D — Cliente con propuesta activa (evitar duplicados)

**Cliente:** CLI012 — Alejandro Vargas Ríos  
**Perfil:** Etapa administrativa, ya tiene una propuesta `plan_pagos` enviada pendiente.  
**Esperado:** El agente detecta la propuesta activa en el contexto y elige una acción  
diferente a `generar_propuesta` (probablemente `registrar_contacto` para dar seguimiento).

In [13]:
ctx_012 = consultar_cliente("CLI012")
print(f"CLI012 — {ctx_012.nombre}")
print(f"Propuestas activas: {len(ctx_012.propuestas_activas)}")
for p in ctx_012.propuestas_activas:
    print(f"  {p.tipo} ${p.monto_propuesto:,.0f} / {p.plazo_meses}m → {p.estado}")
print()

print("Ejecutando agente para CLI012...")
print("=" * 60)
resultado_d = ejecutar_agente("CLI012", modo_autonomo=False)

print(f"Acción tomada:     {resultado_d.accion_tomada}")
print(f"Urgencia:          {resultado_d.urgencia}")
print(f"Resultado OK:      {resultado_d.resultado_ok}")
print(f"Mensaje:           {resultado_d.mensaje_resultado}")
print()
print("Razonamiento:")
print(resultado_d.razonamiento)

CLI012 — Alejandro Vargas Ríos
Propuestas activas: 1
  plan_pagos $15,000 / 6m → enviada

Ejecutando agente para CLI012...
============================================================
Acción tomada:     escalar_caso
Urgencia:          alta
Resultado OK:      True
Mensaje:           Caso escalado a legal. Trigger autónomo suspendido. Requiere resolución humana desde Tab 6.

Razonamiento:
Cliente presenta riesgo crítico: 65 días de mora (>60 días = incumplimiento grave), EWS 0.85 (riesgo moderado-alto), monto significativo ($53,200 = 26.6% del límite), 5 intentos fallidos sin respuesta en 20 días, y propuesta enviada sin confirmación de recepción. La disposición de pago mencionada no se ha materializado. Etapa administrativa ha agotado su efectividad. Transición a judicial es procedente bajo normativa CNBV para créditos en mora >60 días. Requiere: (1) Notificación formal documentada cumpliendo derechos del deudor, (2) Asignación a gestor humano para maximizar último contacto efectivo, (3) Respeto estricto a horarios y frecuencia de contacto, (4) Documentación exhaustiva para sustentación judicial. Sin contexto normativo disponible, se aplican estándares CNBV vigentes para microfinanzas.

## 8 · Lote EWS — Procesamiento serial batch

Simula el trigger diario del EWS: una lista de clientes en riesgo procesados  
en serie. Este es el punto de entrada principal del agente en producción.

**Diseño serial deliberado:** más simple, auditable, suficiente para portfolios demo  
y producción de escala pequeña. `asyncio` está documentado como mejora futura  
para portfolios > 500 clientes concurrentes.

In [14]:
# Subconjunto representativo del EWS — una muestra de cada etapa
LOTE_EWS = [
    "CLI001",   # preventiva, caso limpio
    "CLI006",   # temprana, varios intentos fallidos
    "CLI007",   # temprana, promesa incumplida
    "CLI008",   # temprana, historial corto
    "CLI015",   # administrativa, propuesta activa
]

print(f"Procesando lote de {len(LOTE_EWS)} clientes (modo asistido)...")
print("=" * 60)

resultados_lote = ejecutar_lote_ews(LOTE_EWS, modo_autonomo=False)

# Mostrar resumen en DataFrame
resumen = []
for r in resultados_lote:
    resumen.append({
        "cliente_id":    r.cliente_id,
        "accion":        r.accion_tomada,
        "urgencia":      r.urgencia,
        "ok":            r.resultado_ok,
        "pausa":         r.requiere_confirmacion,
        "error":         r.error or "",
        "mensaje":       r.mensaje_resultado[:60] if r.mensaje_resultado else "",
    })

df_lote = pd.DataFrame(resumen)
display(df_lote)
print()
print(f"Acciones ejecutadas:  {df_lote['ok'].sum()}/{len(df_lote)}")
print(f"Con errores:          {df_lote['error'].astype(bool).sum()}")
print(f"Requieren pausa:      {df_lote['pausa'].sum()}")

Procesando lote de 5 clientes (modo asistido)...
============================================================

,cliente_id,accion,urgencia,ok,pausa,error,mensaje
0,CLI001,sin_accion,media,False,False,,
1,CLI006,sin_accion,alta,False,False,,
2,CLI007,registrar_contacto,alta,True,False,,Contacto registrado. Canal: llamada | Resultado: no_contesto
3,CLI008,registrar_contacto,media,True,False,,Contacto registrado. Canal: llamada | Resultado: no_contesto
4,CLI015,registrar_contacto,alta,True,False,,Contacto registrado. Canal: llamada | Resultado: no_contesto

Acciones ejecutadas:  3/5
Con errores:          0
Requieren pausa:      0

In [15]:
# Distribución de acciones tomadas
print("Distribución de acciones en el lote:")
print(df_lote["accion"].value_counts().to_string())
print()
print("Distribución de urgencias:")
print(df_lote["urgencia"].value_counts().to_string())

Distribución de acciones en el lote:
accion
registrar_contacto    3
sin_accion            2

Distribución de urgencias:
urgencia
alta     3
media    2

## 9 · Análisis del log de decisiones

El `log_decisiones` es la fuente de verdad del razonamiento del agente.  
Cada acción tiene su registro: qué tool eligió, con qué argumentos, qué resultado  
obtuvo y por qué lo decidió. Esto permite auditar el comportamiento del agente  
en cualquier momento sin reconstruir el estado de la sesión.

In [16]:
con = sqlite3.connect(get_db_path())

df_log = pd.read_sql(
    """
    SELECT
        l.log_id,
        l.cliente_id,
        c.nombre,
        c.etapa_cobranza,
        l.tool_llamada,
        l.status,
        l.timestamp,
        SUBSTR(l.razonamiento, 1, 80) as razonamiento
    FROM log_decisiones l
    JOIN clientes c ON l.cliente_id = c.cliente_id
    ORDER BY l.timestamp DESC
    """,
    con
)
con.close()

print(f"Total de decisiones registradas: {len(df_log)}")
print()
display(df_log)

Total de decisiones registradas: 7

,log_id,cliente_id,nombre,etapa_cobranza,tool_llamada,status,timestamp,razonamiento
0,LOG40A2A823,CLI015,Verónica Reyes Luna,administrativa,registrar_contacto,ok,2026-06-08 16:33:40,Cliente con 72 días de mora (2.4 meses) representa riesgo crítico. EWS Score...
1,LOG8ABB9C76,CLI008,Fernando Torres Gil,temprana,registrar_contacto,ok,2026-06-08 16:33:30,El cliente presenta mora de 32 días (dentro del rango de etapa temprana: 30-...
2,LOGF7DA28DC,CLI007,Laura Martínez Soto,temprana,registrar_contacto,ok,2026-06-08 16:33:22,El cliente presenta EWS Score de 0.800 (riesgo muy alto) con 25 días de mora...
3,LOG7C587B02,CLI012,Alejandro Vargas Ríos,administrativa,escalar_caso,ok,2026-06-08 16:32:55,Cliente presenta riesgo crítico: 65 días de mora (>60 días = incumplimiento ...
4,LOGA87AF076,CLI006,Roberto Jiménez Cruz,temprana,escalar_caso,ok,2026-06-08 16:32:29,Cliente presenta EWS Score elevado (0.780) indicando riesgo significativo. C...
5,LOG746633CD,CLI006,Roberto Jiménez Cruz,temprana,registrar_contacto,ok,2026-06-05 16:32:14,Cliente sin respuesta en 5 intentos. Canal SMS como último intento antes de ...
6,LOGC06815DD,CLI012,Alejandro Vargas Ríos,administrativa,generar_propuesta,ok,2026-05-29 16:32:14,Cliente mostró disposición de pago en contacto previo. EWS score 0.85 indica...

In [17]:
# Estadísticas del log
con = sqlite3.connect(get_db_path())

print("Decisiones por status:")
df_status = pd.read_sql(
    "SELECT status, COUNT(*) as total FROM log_decisiones GROUP BY status", con
)
display(df_status)

print()
print("Tools más usadas por el agente:")
df_tools = pd.read_sql(
    """SELECT tool_llamada, COUNT(*) as veces, 
       SUM(CASE WHEN status='ok' THEN 1 ELSE 0 END) as exitosas
       FROM log_decisiones 
       WHERE tool_llamada IS NOT NULL
       GROUP BY tool_llamada ORDER BY veces DESC""",
    con
)
display(df_tools)
con.close()

Decisiones por status:

  status  total
0     ok      7

Tools más usadas por el agente:

         tool_llamada  veces  exitosas
0  registrar_contacto      4         4
1        escalar_caso      2         2
2   generar_propuesta      1         1

## 10 · Estado del CRM después de las ejecuciones

Verificamos que el CRM refleja correctamente todos los efectos de las acciones  
ejecutadas por el agente: nuevos contactos, cambios de etapa, escalaciones, propuestas.

In [18]:
con = sqlite3.connect(get_db_path())

print("Contactos registrados por el agente (agente='Agente_L3', recientes):")
df_contactos = pd.read_sql(
    """SELECT c.cliente_id, cl.nombre, c.canal, c.resultado, c.timestamp
       FROM contactos c
       JOIN clientes cl ON c.cliente_id = cl.cliente_id
       WHERE c.agente = 'Agente_L3'
       ORDER BY c.timestamp DESC LIMIT 10""",
    con
)
display(df_contactos)

print()
print("Escalaciones activas (pendientes de resolución humana):")
df_esc = pd.read_sql(
    """SELECT e.escalacion_id, e.cliente_id, c.nombre,
       c.etapa_cobranza, e.nivel, e.estado, e.timestamp
       FROM escalaciones e
       JOIN clientes c ON e.cliente_id = c.cliente_id
       WHERE e.estado = 'pendiente'
       ORDER BY e.timestamp DESC""",
    con
)
display(df_esc)

print()
print("Propuestas activas (enviadas, sin respuesta):")
df_prop = pd.read_sql(
    """SELECT p.propuesta_id, p.cliente_id, c.nombre,
       p.tipo, p.monto_propuesto, p.plazo_meses, p.estado, p.timestamp
       FROM propuestas p
       JOIN clientes c ON p.cliente_id = c.cliente_id
       WHERE p.estado = 'enviada'
       ORDER BY p.timestamp DESC""",
    con
)
display(df_prop)
con.close()

Contactos registrados por el agente (agente='Agente_L3', recientes):

  cliente_id                nombre     canal    resultado            timestamp
0     CLI015   Verónica Reyes Luna   llamada  no_contesto  2026-06-08 16:33:40
1     CLI008   Fernando Torres Gil   llamada  no_contesto  2026-06-08 16:33:30
2     CLI007   Laura Martínez Soto   llamada  no_contesto  2026-06-08 16:33:22
3     CLI001      Ana García Reyes   llamada     contesto  2026-06-06 12:32:14
4     CLI001      Ana García Reyes       sms  no_contesto  2026-06-05 14:32:14
5     CLI006  Roberto Jiménez Cruz       sms  no_contesto  2026-06-05 14:32:14
6     CLI003   Sofía Herrera López       sms  no_contesto  2026-06-01 13:32:14
7     CLI006  Roberto Jiménez Cruz   llamada     contesto  2026-06-01 11:32:14
8     CLI006  Roberto Jiménez Cruz  whatsapp  no_contesto  2026-05-29 15:32:14
9     CLI007   Laura Martínez Soto       sms  no_contesto  2026-05-26 14:32:14

Escalaciones activas (pendientes de resolución humana):

  escalacion_id cliente_id                 nombre  etapa_cobranza       nivel     estado            timestamp
0   ESC37A82195     CLI012  Alejandro Vargas Ríos  administrativa       legal  pendiente  2026-06-08 16:32:55
1   ESCB0DC0371     CLI006   Roberto Jiménez Cruz        temprana  supervisor  pendiente  2026-06-08 16:32:29
2   ESCD3A0BEA3     CLI014     Héctor Guzmán Lara  administrativa  supervisor  pendiente  2026-05-24 16:32:14
3   ESC1CC316C7     CLI016  Arturo Medina Fuentes        judicial       legal  pendiente  2026-05-09 16:32:14
4   ESCF0BAF7CA     CLI018   Luis Cervantes Vidal        judicial       legal  pendiente  2026-04-24 16:32:14

Propuestas activas (enviadas, sin respuesta):

,propuesta_id,cliente_id,nombre,tipo,monto_propuesto,plazo_meses,estado,timestamp
0,PROE9E47F63,CLI015,Verónica Reyes Luna,plan_pagos,8000.0,4,enviada,2026-05-31 16:32:14
1,PRO4919CCD2,CLI012,Alejandro Vargas Ríos,plan_pagos,15000.0,6,enviada,2026-05-29 16:32:14
2,PROA4EF67DA,CLI019,Rosa Pacheco Ávila,quita,10000.0,1,enviada,2026-05-27 16:32:14

## 11 · Validación final — checklist del Level 3

Confirmamos que el agente cumple los criterios que lo definen como Level 3  
(no Level 2) según el framework de autonomía.

In [19]:
con = sqlite3.connect(get_db_path())
n_log     = con.execute("SELECT COUNT(*) FROM log_decisiones WHERE status='ok'").fetchone()[0]
n_cont    = con.execute("SELECT COUNT(*) FROM contactos WHERE agente='Agente_L3'").fetchone()[0]
n_esc     = con.execute("SELECT COUNT(*) FROM escalaciones WHERE estado='pendiente'").fetchone()[0]
n_prop    = con.execute("SELECT COUNT(*) FROM propuestas").fetchone()[0]
con.close()

checklist = [
    ("Tool calling con efectos persistentes en DB",
     n_cont > 0 or n_prop > 0,
     f"{n_cont} contactos + {n_prop} propuestas en CRM"),
    ("Decisión autónoma de qué acción tomar",
     n_log > 0,
     f"{n_log} decisiones registradas en log_decisiones"),
    ("Trazabilidad completa del razonamiento",
     n_log > 0,
     "Cada acción tiene razonamiento, tool, argumentos y resultado en log"),
    ("Mecanismo de pausa para casos críticos",
     True,
     "Reglas explícitas: judicial | monto>50k | intentos>=5"),
    ("Bloqueo para clientes gestionados por humano",
     True,
     "gestionado_humano=True → tool_call=None → END directo"),
    ("Manejo de errores técnicos sin romper el grafo",
     True,
     "edge fallo → registrar_error → END siempre limpio"),
]

print(f"{'Criterio Level 3':<45} {'Estado':<6} {'Evidencia'}")
print("-" * 100)
for criterio, cumple, evidencia in checklist:
    marca = "  ✓" if cumple else "  ✗"
    print(f"{criterio:<45} {marca}    {evidencia}")

total = sum(1 for _, c, _ in checklist if c)
print()
print(f"Criterios cumplidos: {total}/{len(checklist)}")
if total == len(checklist):
    print("✓ El agente cumple todos los criterios de Level 3.")

Criterio Level 3                              Estado Evidencia
----------------------------------------------------------------------------------------------------
Tool calling con efectos persistentes en DB     ✓    41 contactos + 5 propuestas en CRM
Decisión autónoma de qué acción tomar           ✓    7 decisiones registradas en log_decisiones
Trazabilidad completa del razonamiento          ✓    Cada acción tiene razonamiento, tool, argumentos y resultado en log
Mecanismo de pausa para casos críticos          ✓    Reglas explícitas: judicial | monto>50k | intentos>=5
Bloqueo para clientes gestionados por humano    ✓    gestionado_humano=True → tool_call=None → END directo
Manejo de errores técnicos sin romper el grafo   ✓    edge fallo → registrar_error → END siempre limpio

Criterios cumplidos: 6/6
✓ El agente cumple todos los criterios de Level 3.

## 12 · Próximos pasos

Con el grafo validado en este notebook, la **Fase 4** integra el agente en `tab_cobranza.py`:

1. **Toggle modo autónomo** en Tab 6 — activa `ejecutar_agente(..., modo_autonomo=True)`.  
   Si `requiere_confirmacion=True`, mostrar botón de aprobación antes de ejecutar.

2. **Panel de escalaciones pendientes** — listar casos con `estado='pendiente'` en la  
   tabla `escalaciones` y botón de resolución que actualiza `resuelto_por` y `fecha_resolucion`.

3. **Tabla de log en vivo** — mostrar `log_decisiones` en tiempo real para que el  
   supervisor audite las decisiones del agente sin salir del dashboard.

4. **Trigger EWS desde Tab 6** — botón que llama `ejecutar_lote_ews()` con los  
   clientes que el EWS marcó como en riesgo en la última corrida del batch.